### ISSUE TITLE
How to understand the example usage of hle

### ISSUE THREAD

**Issue by dreamerlzl** [andikleen/tsx-tools#11]
For the example provided in the readme, 
```C
    #include "hle-emulation.h"
    #include "immintrin.h"  /* for _mm_pause() */

    static volatile int lock;

    /* Take elided lock */
    while (__hle_acquire_test_and_set(&lock) == 1) {
            while (lock == 0)
                    _mm_pause();
    }
    ...
    /* Release elided lock */
    __hle_release_clear(&lock);
```
why shall we check (lock == 0) when we fail to acquire the lock? Isn't it the case that a set lock should be something non-zero?

**Comment by andikleen** [comment]
On Tue, Feb 25, 2020 at 07:43:35AM -0800, dreamerlzl wrote:
> For the example provided in the readme,
> 
>     #include "hle-emulation.h"
>     #include "immintrin.h"  /* for _mm_pause() */
> 
>     static volatile int lock;
> 
>     /* Take elided lock */
>     while (__hle_acquire_test_and_set(&lock) == 1) {
>             while (lock == 0)
>                     _mm_pause();
>     }
>     ...
>     /* Release elided lock */
>     __hle_release_clear(&lock);
> 
> why shall we check (lock == 0) when we fail to acquire the lock? Isn't it the
> case that a set lock should be something non-zero?

You're right. The example is wrong. Should check for lock != 0.

Will fix thanks.
