### ISSUE TITLE
make command error

### ISSUE THREAD

**Issue by chandru-kumar** [andikleen/tsx-tools#13]
Hi Team,

I get below error when i run make command..
![make error](https://user-images.githubusercontent.com/26222838/109759244-b7cf3e00-7c12-11eb-8819-7de9e8fb64a8.PNG)
This repo do not have proper setup guide and required softwares to run this code. Can you pls update that as well?

**Comment by andikleen** [comment]
On Tue, Mar 02, 2021 at 09:52:51PM -0800, Chandru Kumar R wrote:
> Hi Team,
> 
> I get below error when i run make command..
> make error

Can you paste the error?

**Comment by chandru-kumar** [comment]
C:\tsx-tools-master\tsx-tools-master>make
gcc -fPIC -shared -g -o ignore-xend.so ignore-xend.c
ignore-xend.c:27:30: error: unknown type name 'siginfo_t'
   27 | static void handler(int sig, siginfo_t *si, void *ctx_ptr)
      |                              ^~~~~~~~~
ignore-xend.c: In function 'init_sig':
ignore-xend.c:68:9: error: variable 'sa' has initializer but incomplete type
   68 |  struct sigaction sa = {
      |         ^~~~~~~~~
ignore-xend.c:69:4: error: 'struct sigaction' has no member named 'sa_sigaction'
   69 |   .sa_sigaction = handler,
      |    ^~~~~~~~~~~~
ignore-xend.c:69:19: error: 'handler' undeclared (first use in this function)
   69 |   .sa_sigaction = handler,
      |                   ^~~~~~~
ignore-xend.c:69:19: note: each undeclared identifier is reported only once for each function it appears in
ignore-xend.c:69:19: warning: excess elements in struct initializer
ignore-xend.c:69:19: note: (near initialization for 'sa')
ignore-xend.c:70:4: error: 'struct sigaction' has no member named 'sa_flags'
   70 |   .sa_flags = SA_SIGINFO
      |    ^~~~~~~~
ignore-xend.c:70:15: error: 'SA_SIGINFO' undeclared (first use in this function)
   70 |   .sa_flags = SA_SIGINFO
      |               ^~~~~~~~~~
ignore-xend.c:70:15: warning: excess elements in struct initializer
ignore-xend.c:70:15: note: (near initialization for 'sa')
ignore-xend.c:68:19: error: storage size of 'sa' isn't known
   68 |  struct sigaction sa = {
      |                   ^~
ignore-xend.c:73:2: warning: implicit declaration of function 'sigaction' [-Wimplicit-function-declaration]
   73 |  sigaction(SIGSEGV, &sa, NULL);
      |  ^~~~~~~~~
make: *** [Makefile:7: ignore-xend.so] Error 1

**Comment by chandru-kumar** [comment]
Can you pls provide a setup guide as well?

**Comment by andikleen** [comment]
On Wed, Mar 03, 2021 at 08:19:34AM -0800, Chandru Kumar R wrote:
> C:\tsx-tools-master\tsx-tools-master>make

You're building on Windows. This is a Linux package.

That said it might work if you ignore the error with -k. ignore-xend
is an optional standalone module and probably not needed.

**Comment by chandru-kumar** [comment]
Thank you!
